JavaScript capstone project - Your API-based webapp
ZewdieMc/BiteBuddy pull request #40
Opened 2023-03-17 20:29 UTC by ZewdieMc

## Hey Reviewer :wave: 
In this PR, we implemented the following [project requirements](https://github.com/microverseinc/curriculum-javascript/blob/main/group-capstone/js_capstone.md).

**General requirements**

- Make sure that there are [no linter errors](https://github.com/microverseinc/linters-config).
- Make sure that you used correct [Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md).

- Make sure that you documented your work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).

**HTML/CSS & JavaScript requirements**

- Follow our list of [best practices for HTML & CSS](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).
- Follow our list of [best practices for JavaScript](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md).

**Project requirements**

**APIs**
We choose [Meals DB](https://www.themealdb.com/api.php): data about meals as our base API.

**Interfaces**

- We build these interfaces:
  - The home page.
  - The comments popup.
- We followed the layout of the wireframe provided
- Home page
  - When the page loads, the web app retrieves data from:
    - The [Meals DB](https://www.themealdb.com/api.php) API and shows the list of items on screen.
    - The Involvement API to show the item likes. 
  - When the user clicks on the Like button of an item, the interaction is recorded in the Involvement API and the screen is updated.
  - When the user clicks on the "Comments" button, the Comments popup appears.

- Comments popup
  - When the page loads, the web app retrieves data from:
    - The [Meals DB](https://www.themealdb.com/api.php) API and shows the list of items on the screen.
    - The Involvement API to show the item comments. 
  - When the user clicks on the comment button, the interaction is recorded in the Involvement API and the screen is updated.
  - When the user clicks on the "Comments" button, the Comments popup appears.

**Counters** 
We implemented two functions that show : 

- The number of items on the home page
- The number of comments in the comments popup page
and we tested the two functions using Jest.

2023-03-17 22:46 UTC, OyePriscilla requested changes
Hi @ZewdieMc and @lorenzoworx 👏 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
Use async and await with the fetch method to send and receive data from API ✔️ 
Set up webpack and JS testing library (Jest) ✔️ 
Implement modules for App counter ✔️ 
App work as expected ✔️ 
All test passed ✔️ 
Understand single page web App ✔️ 


## Required Changes ♻️

- [ ] For the video presentation, please kindly **show the piece of code that you find interesting** according to the project requirement. Thanks. 👍 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-17 22:46 UTC, OyePriscilla commented on src/modules/involvement.js
> +/* eslint-disable camelcase, no-console */
- [ ] Please, I think it will be great if you don't disable this linter, I believe you can work around how to resolve the issue the linter is pointing at. One of the importance of linters is to identify certain programming errors earlier on that you may not have noticed while writing code. 👍

2023-03-17 22:46 UTC, OyePriscilla commented on src/index.html
> +            <a href="#">Menus</a>
- [ ] For semantics purpose, kindly  define the `ul` tag, which is used to show the unordered list. And, then  define the list items in the `li` tag. 👍

2023-03-18 11:42 UTC, ZewdieMc commented on src/index.html
> +            <a href="#">Menus</a>
Hi @OyePriscilla :wave: 
Change [implemented](8e6b60ffe31a6bcaeddebe45a6823b9db834f956).

2023-03-18 11:45 UTC, ZewdieMc commented on src/modules/involvement.js
> +/* eslint-disable camelcase, no-console */
Fixed, please [have a look](https://github.com/ZewdieMc/javascript-group-capstone/pull/40/commits/015794abdba52acf181426c77742aa78dc1286bb).

2023-03-18 12:01 UTC, huseyinbiyik approved these changes
Hi @ZewdieMc & @lorenzoworx 
You did a great job guys. All looks good and works as intended. 💯 

## ✔️ Status: APPROVED 🏆 🎉 🎊

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Alt Text](https://media.giphy.com/media/wZjlCH43M3M0U/giphy.gif)



## Highlights
- You followed git flow and reviewed each other's PRs 💯 
- Video fixed with the requirements from the previous reviewer's request 👍 
- The design looks minimal and cool 😎 
- Linter set up well and checks pass 🟢
- Commit messages are meaningful and written in imperative tense 📝
- PR description is descriptive 📝
- Great implementation of the requested changes of previous reviewers 🕸️

## Optional suggestions
- I highly recommend you to get familiar with Figma for your next project. It is becoming industry standard tool for sharing video notes and presentations 👍 
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-18 12:19 UTC, merged

2023-03-18 21:45 UTC, OyePriscilla commented on src/index.html
> +            <a href="#">Menus</a>
@ZewdieMc 👍